name: 📦 Deploy to VS Code Marketplace

on:
  push:
    branches:
      - main
  
jobs:
  build-major:
    #if: ${{ contains(github.event.head_commit.message, 'major')}}
    runs-on: ubuntu-latest
    steps:
      - run: git config --global user.email "brunosilv_a@outlook.com"
      - run: git config --global user.name "Bruno Silva"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
        name: 📩 Update npm
      - run: npm install -g npm  # Adding a cmd to update the npm version of the server
        name: 📦 Installing vsce package
      - run: npm install -g vsce@1.96.1 --save-dev
        name: ✅ Publishing on marketplace
      - run: vsce publish major -p ${{ secrets.AZURE_SECRET }}
      
  build-minor:
    #if: ${{ contains(github.event.head_commit.message, 'minor')}}
    runs-on: ubuntu-latest
    steps:
      - run: git config --global user.email "brunosilv_a@outlook.com"
      - run: git config --global user.name "Bruno Silva"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
        name: 📩 Update npm
      - run: npm install -g npm  # Adding a cmd to update the npm version of the server
        name: 📦 Installing vsce package
      - run: npm install -g vsce@1.96.1 --save-dev
        name: ✅ Publishing on marketplace
      - run: vsce publish minor -p ${{ secrets.AZURE_SECRET }}

  build-patch:
    #if: ${{ contains(github.event.head_commit.message, 'patch')}}
    runs-on: ubuntu-latest
    steps:
      - run: git config --global user.email "brunosilv_a@outlook.com"
      - run: git config --global user.name "Bruno Silva"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
        name: 📩 Update npm
      - run: npm install -g npm  # Adding a cmd to update the npm version of the server
        name: 📦 Installing vsce package
      - run: npm install -g vsce@1.96.1 --save-dev
        name: ✅ Publishing on marketplace
      - run: vsce publish patch -p ${{ secrets.AZURE_SECRET }}