name: 📦 Deploy

on:
  push:
    branches:
      - main
  
jobs:
  build-base:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        semantic: [major, minor, patch]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'  
      - uses: haya14busa/action-cond@v1
        id: condval
        with:
          cond: ${{ startsWith(github.event.head_commit.message, matrix.semantic) }}
          if_true: 'true'
          if_false: 'false'
      - name: 📦 Verify scope
        run: echo "${{ github.event.head_commit.message }}"
      - name: 📦 Installing vsce package
        run: npm install -g vsce@1.96.1 --save-dev
      - name: ✅ Publishing on Marketplace
        if: | 
          steps.condval.outputs.value == 'true'
        run: |
          vsce publish ${{ matrix.semantic }} -p ${{ secrets.AZURE_SECRET }}
