name: 📦 Deploy to VS Code Marketplace

on:
  push:
    branches:
      - main
  
jobs:
  build-major:
    # Run if there is any substring "major" in the commit message
    if: ${{ contains(github.event.head_commit.message, 'major')}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
        name: 📦 Installing vsce package
      - run: npm install -g vsce@1.96.1 --save-dev
        name: 🔧 Generate vsix package
      - run: vsce package
        name: ✅ Publishing on marketplace
      #- run: vsce publish major -p ${{ secrets.AZURE_SECRET }}

  build-minor:
  # Run if there is any substring "minor" in the commit message
    if: ${{ contains(github.event.head_commit.message, 'minor')}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
        name: 📦 Installing vsce package
      - run: npm install -g vsce@1.96.1 --save-dev
        name: 🔧 Generate vsix package
      - run: vsce package
        name: ✅ Publishing on marketplace
      #- run: vsce publish minor -p ${{ secrets.AZURE_SECRET }}

  build-patch:
  # Run if there is any substring "path" in the commit message
    if: ${{ contains(github.event.head_commit.message, 'patch')}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
        name: 📦 Installing vsce package
      - run: npm install -g vsce@1.96.1 --save-dev
        name: 🔧 Generate vsix package
      - run: vsce package
        name: ✅ Publishing on marketplace
      #- run: vsce publish patch -p ${{ secrets.AZURE_SECRET }}